development:
  secret_key_base: 'xxx'
  publishable_key: pk_test_kfSdLJDfrBkyze237lY08faP
  secret_key: sk_test_hCHKPGauuyzHP92S8kPW2InB
production:
  secret_key_base: 'xxx'
  publishable_key: pk_live_ZUll49EYvO0kpTuNWnYJwhEA
  secret_key: sk_live_9jx5rlUEA7dRv0AQEpSCD9Tq